### ISSUE TITLE
VL-BERT with other dataset

### ISSUE THREAD

**Issue by yellowjs0304** [jackroos/VL-BERT#13]
Hi, Thank you for sharing nice work. 
It seems really good at vision and Language multi-grounding.
I wanna check the performance with other tasks.
What should i follow, if i wanna pre-train the model with another dataset?
Thank you.

**Comment by jackroos** [comment]
@yellowjs0304 Thanks for your interest! You should write your own dataset following the output format of [ConceptualCaptionsDataset](https://github.com/jackroos/VL-BERT/blob/76caf782311a629366303edeb815d296a168cc70/pretrain/data/datasets/conceptual_captions.py#L19).

**Comment by yellowjs0304** [comment]
Thank you for kindly reply. It is really helpful.
