### ISSUE TITLE
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by beckyli** [jackroos/VL-BERT#16]
Dear Author,

When I try to run " generate_tsv_v2_1.py", I meet the problem "Check failed: error == cudaSuccess (2 vs. 0)  out of memory".  
My GPU is 11G Tesla K40m. I have changed the batch_size to 1, but the problem is still there
Do you know how to solve the problem? Thanks a lot!

**Comment by jackroos** [comment]
@beckyli Could you please list the version of your system, cuda and cudnn?

**Comment by beckyli** [comment]
@jackroos I am using nivida-docker which is built on Ubuntu18.04. 
Cuda: cuda compilation tools, release 9.0, V9.0.176
cudnn: CUDNN_MAJOR 7

**Comment by jackroos** [comment]
@beckyli Could you try Ubuntu 16.04 docker?
