### ISSUE TITLE
Google drive access rights for en_corpus

### ISSUE THREAD

**Issue by sileod** [jackroos/VL-BERT#17]
Hi, thank you for making this code available !
I can download the en_corpus .dioc files (bookcorpus, wikipedia) from my PC, but I want them on a server an have to use a bash wget command; when I use the "gdown" library, the command don't work because the permission level seems insufficient
`Maybe you need to change permission over 'Anyone with the link'?``
Can you please change the accessibility level or help me find a way to download the corpus from command line ? Thanks!

**Comment by jackroos** [comment]
@sileod I remember that I could download the files using gdown, and the permission should be already set to "anyone with the link", could you download your other files I shared using gdown?

**Comment by sileod** [comment]
I did not copy the full ID, it actually works, sorry...
