### ISSUE TITLE
About the updown feature box size for each image

### ISSUE THREAD

**Issue by Wangt-CN** [jackroos/VL-BERT#19]
Hi, Thanks for your great work.
From the `generate_tsv_v2.py` file, it is seemed that you have used the 10-36 boxes for each image?
However, in your paper, you have wrote "at most 100 RoIs are selected...."

Have I missed anything?
Thanks

**Comment by jackroos** [comment]
@Wangt-CN Sorry for the mistake in the code we provided. Actually we use 10-100 boxes in our experiment.  For now, you can simply set ```MAX_BOXES=100``` in ```generate_tsv_v2.py```. We would update the code soon! 
Thanks for your kind reminder!

**Comment by jackroos** [comment]
I have updated the box number in [another repo](https://github.com/jackroos/bottom-up-attention) and also the link in ReadMe for Conceptual Captions.
