### ISSUE TITLE
VL-BERT(base with pretraining) and VL-BERT large

### ISSUE THREAD

**Issue by Frankszc** [jackroos/VL-BERT#20]
Hi, Thanks for the great repo.
I wonder that do we need to pretrain model again if  I want to apply VL-BERT(base with pretraining) or  VL-BERT large to vcr task? Thanks a lot!

**Comment by jackroos** [comment]
No. We have provided pre-trained models. Please see [this page](https://github.com/jackroos/VL-BERT/blob/master/model/pretrained_model/PREPARE_PRETRAINED_MODELS.md) for details. Thanks!

**Comment by Frankszc** [comment]
> No. We have provided pre-trained models. Please see this page for details. Thanks!

ok，thanks！
