### ISSUE TITLE
Fine-tuned model for different tasks?

### ISSUE THREAD

**Issue by GavinGuan95** [jackroos/VL-BERT#21]
There is a list of fine-tined models in:
https://github.com/jackroos/VL-BERT/blob/master/model/pretrained_model/PREPARE_PRETRAINED_MODELS.md

But it looks like some of the fine-tuned model is not here, for example the VQA model. Is this intentional?

**Comment by jackroos** [comment]
@GavinGuan95 Actually those models are pre-trained models, not fine-tuned models. Here 'pre-trained' means pre-training on Conceptual Captions dataset together with text-only corpus.
