### ISSUE TITLE
anyone can help me：error：ImportError:  C_ROIPooling.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E

### ISSUE THREAD

**Issue by jingquanliang** [jackroos/VL-BERT#23]
when i run  the code， the error occures：
![image](https://user-images.githubusercontent.com/8544622/79060964-9f35fc80-7cbd-11ea-914d-0888faca647d.png)

**Comment by jackroos** [comment]
@jingquanliang Could you please provide your version of gcc, nvcc, python and pytorch?

**Comment by jingquanliang** [comment]
thank u，i changed the cuda version， it works now
