### ISSUE TITLE
torchvision dependency

### ISSUE THREAD

**Issue by runxiao** [jackroos/VL-BERT#26]
I follow the document to install VL-BERT, then run scripts
'./scripts/dist_run_single.sh 4 vcr/train_end2end.py ./cfgs/vcr/base_q2a_4x16G_fp32.yaml ./'
Got this error:
![image](https://user-images.githubusercontent.com/26789124/80208968-cb5d6000-8663-11ea-9606-2096caccd15c.png)

**Comment by jackroos** [comment]
You may try to reinstall torchvision by:
```bash
pip uninstall torchvision; pip install torchvision==0.2.1
```

**Comment by runxiao** [comment]
> You may try to reinstall torchvision by:
> 
> ```shell
> pip uninstall torchvision; pip install torchvision==0.2.1
> ```

I reinstall torchvision, but still get the same error

**Comment by jackroos** [comment]
@runxiao I think it is problems from installing torchvision. You could open an issue in torchvision github repo. Thanks!
