### ISSUE TITLE
Visualizing attention per head and per layer

### ISSUE THREAD

**Issue by jules-samaran** [jackroos/VL-BERT#27]
Dear authors, thank you for your great work and making it available.

I'm currently using vl-bert and I'd like to visualize attention to make sure my model is learning from images and text jointly and not independently. I've tried using the visualization tool available in the notebook under ./viz however it only provides a birds-eye view of attention across all of the model’s layers and heads. I'd be interested in looking at something that looks more like what you show in the Figure 2 of the README with the text and ROI label on each side and focusing on one attention head and one layer at a time. Can this be plotted from some code I haven't found yet in the repo?

**Comment by jackroos** [comment]
In the birds-eye view, you can click on a head, then zoomed view of that head would be show. And you can choose text -> roi in the top of birds-eye view to show text to roi attention like ReadMe.

**Comment by jules-samaran** [comment]
Sorry I had missed this, thank you!
