### ISSUE TITLE
Miss the [SEQ] token when truncating the sequence too long

### ISSUE THREAD

**Issue by weiyx16** [jackroos/VL-BERT#28]
I found a little mistake when **loading the data from multimodal dataset**, for example the CC. I'm not sure whether it will make a big difference.
Ref to you src paper, the pretrain input is in the format of **[CLS] + Caption Tokens + [SEQ] + ROIs + [END]** and I also noticed that when the input sequence is over long, the code will truncate the sequence to max_len, e.g. 64, at [here](https://github.com/jackroos/VL-BERT/blob/master/pretrain/data/datasets/conceptual_captions.py#L216). My question is, when the code do text truncation, like
```python
text = text[:text_len_keep]
mlm_labels = mlm_labels[:text_len_keep]
```
The text has already added [CLS] & [SEQ] in the beginning and end, so this truncation op will definitely **Move Out the [SEQ] Token**. I don't know whether this small mistake matters. But to keep input format, it's better to **truncate the input caption tokens first, then add [CLS] & [SEQ], then convert to ids..**
Thank you for your reply in advance

**Comment by jackroos** [comment]
@weiyx16 Thank you for pointing out this small bug. Yeah, actually I have also found this bug but I forgot to update the repo. Sorry, I would update the code soon.

**Comment by jackroos** [comment]
I have updated the code. Thanks again!

**Comment by weiyx16** [comment]
Thank you for your reply!
