### ISSUE TITLE
pretrained model for conceptual-captions

### ISSUE THREAD

**Issue by SnoopyMark** [jackroos/VL-BERT#29]
In .\VL-BERT-master\data\conceptual-captions\ReadMe.txt there is a request in step 8(3): "Download pretrained model (https://www.dropbox.com/s/wqada4qiv1dz9dk/resnet101_faster_rcnn_final.caffemodel?dl=1)", which is not available now.
Could you please provide another solution?
Thx!

**Comment by jackroos** [comment]
@SnoopyMark I have updated the link in ReadMe, now you should be able to download the model.

**Comment by SnoopyMark** [comment]
Nice, thx  bro!
