### ISSUE TITLE
How to generate my own vgbua_res101_precomputed files.

### ISSUE THREAD

**Issue by kememem** [jackroos/VL-BERT#33]
Hi,

When I use your code to evaluate my own visual grounding dataset, could you give me some instructions for constructing vgbua_res101_precomputed files? 

Thanks

**Comment by jackroos** [comment]
You can download the files for VQA ![here](https://github.com/jackroos/VL-BERT/blob/master/data/PREPARE_DATA.md) and following the same format. Thank you!

**Comment by kememem** [comment]
Thanks for the reply. I've checked the files and understand the meaning of most key/value pairs. However, could you explain me what does "boxes" key mean? How can I generate the values of "boxes" from an annotated image. Thanks!

**Comment by jackroos** [comment]
It means the bounding boxes of objects in the image, you can decode the "boxes" following our code of VQA dataset:
https://github.com/jackroos/VL-BERT/blob/d58c70c78bbeb9ff278ee79f93a6a0f02e66a914/vqa/data/datasets/vqa.py#L445
After it is decoded, it should be a numpy array of shape (#boxes, 4). And you can encode boxes of your own image by following way:
https://github.com/jackroos/bottom-up-attention/blob/4de0a37c98039470f27a0cbfa94765e90bb80d24/tools/generate_tsv_v2.py#L98
