### ISSUE TITLE
4-d location vector

### ISSUE THREAD

**Issue by kememem** [jackroos/VL-BERT#36]
Hi,

I am looking at your code. Can you please point me out which part of the code is doing location vector normalization? I can see you pass 4-d raw location into the model, but I could find the place that you normalize it with image width and height.

Thanks!

**Comment by jackroos** [comment]
@kememem 
https://github.com/jackroos/VL-BERT/blob/d58c70c78bbeb9ff278ee79f93a6a0f02e66a914/common/utils/bbox.py#L55

**Comment by kememem** [comment]
Thank you so much for your prompt reply. Can you further elaborate in which file you call this coordinate_embeddings function?

**Comment by jackroos** [comment]
@kememem

https://github.com/jackroos/VL-BERT/blob/d58c70c78bbeb9ff278ee79f93a6a0f02e66a914/common/fast_rcnn.py#L170

Sorry for the late reply.
