### ISSUE TITLE
Using CUDA 10.1

### ISSUE THREAD

**Issue by tejas1995** [jackroos/VL-BERT#37]
Hi, my system has CUDA 10.1, so I followed your setup instructions, but using `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch`. The rest of the installation went fine, but I got the following message when trying to test refcoco+:
`ImportError: VL-BERT/refcoco/../common/lib/roi_pooling/C_ROIPooling.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E`

I think this could be due to the CUDA version mismatch. Do you know if the compiling scripts have to be run differently for CUDA 10.1?

**Comment by jackroos** [comment]
@tejas1995 This error seems related to your compiling environment. Could you provide more information about your environment, like version of your system and gcc? And you can try to compile the operator again by firstly remove the ".so" file and "build" folder under common/lib/roi_pooling, and then run init.sh again, remember to notice if there are any error messages during this process.

**Comment by tejas1995** [comment]
Thanks, removing the .so file and build folder worked.
