### ISSUE TITLE
how much computing resources do you spend to pretrain the model?

### ISSUE THREAD

**Issue by junchen14** [jackroos/VL-BERT#39]
Hi, recently I prepare to pretrain a similar model, I am wondering how much computing resources (the number of gpus, the type of gpu and amount of time). Hope you could answer this question to me.

**Comment by jackroos** [comment]
@junchen14 It takes 2 days for VL-BERT_base and 5.5 days for VL-BERT_large on 16 Tesla V100 (16G) GPUs to conduct the pre-training. By the way, if you freeze the Fast RCNN, the speed would be much faster, it only takes about 30 hours on 4 Tesla V100 (16G) GPUs for VL-BERT_base.

**Comment by junchen14** [comment]
thanks for your info. I appreciate it very much.
