### ISSUE TITLE
Working with CUDA 10.1

### ISSUE THREAD

**Issue by clairecyq** [jackroos/VL-BERT#42]
Hi,
My gcc and Ubuntu versions match exactly those in README.md, but I have CUDA 10.1. I set up the environment exactly as in README.md. 
When trying to run the code, I find CUDA 10.1 causing trouble:
1. if cudatoolkit is not 9.0 -> ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory
2. if cudatoolkit is 9.0 ->  ImportError:.../VL-BERT/refcoco/../common/lib/roi_pooling/C_ROIPooling.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd

Is there any fix other than having to install CUDA 9.0?

**Comment by jackroos** [comment]
You shold install pytorch compiled by cuda 10.1 instead of cuda 9.0 in README like follwing.
conda install pytorch=1.1.0 cudatoolkit=10.1 -c pytorch
