### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by campper** [jackroos/VL-BERT#43]
安装说明也没装成功，真的太郁闷了

**Comment by SnoopyMark** [comment]
2333

**Comment by jackroos** [comment]
Please make sure the environment is same with README, including system, cuda and python. Good luck for you. Thank you.

**Comment by jackroos** [comment]
If you don't provide detailed problems you met, I would close this issue after several days. Thanks!

**Comment by campper** [comment]
我在运行pretrain脚本时， ./scripts/dist_run_single.sh 4 pretrain/train_end2end.py cfgs/pretrain/base_prec_4x16G_fp32.yaml ./
在准备 bottom-up-attention 出现问题
首先，在lib/下 make
![image](https://user-images.githubusercontent.com/12744186/87856067-f39ce800-c94e-11ea-9e19-8fcdf9e439a5.png)
python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
rm -rf build

其次，Build Caffe and pycaffe
执行：make -j8 && make pycaffe
出现
![image](https://user-images.githubusercontent.com/12744186/87856104-49719000-c94f-11ea-96c8-c41655cb38a2.png)
NVCC src/caffe/util/im2col.cu
NVCC src/caffe/util/math_functions.cu
make: /usr/local/cuda/bin/nvcc: Command not found
make: /usr/local/cuda/bin/nvcc: Command not found
Makefile:594: recipe for target '.build_release/cuda/src/caffe/util/im2col.o' failed
make: *** [.build_release/cuda/src/caffe/util/im2col.o] Error 127
make: *** Waiting for unfinished jobs....
Makefile:594: recipe for target '.build_release/cuda/src/caffe/util/math_functions.o' failed
make: *** [.build_release/cuda/src/caffe/util/math_functions.o] Error 127
NVCC src/caffe/layers/concat_layer.cu
make: /usr/local/cuda/bin/nvcc: Command not found
Makefile:594: recipe for target '.build_release/cuda/src/caffe/layers/concat_layer.o' failed
make: *** [.build_release/cuda/src/caffe/layers/concat_layer.o] Error 127

但我的caffe是有的
![image](https://user-images.githubusercontent.com/12744186/87856136-7625a780-c94f-11ea-9f47-f99b282c1481.png)
>caffe version 1.0.0

所以请麻烦指点一下

**Comment by jackroos** [comment]
@campper 看起来是你没有装好cuda。。。无法找到nvcc的命令。你可以通过下面的命令来测试cuda是不是配置好了：
```bash
nvcc -V
```
如果装好了，会显示cuda版本。

**Comment by campper** [comment]
你好，我的机器上有cuda 
![image](https://user-images.githubusercontent.com/12744186/88002758-dbd38880-cb35-11ea-9f80-40e32cce51f4.png)

**Comment by jackroos** [comment]
你可以看看which cuda，看是不是cuda路径和上面编译调用的/usr/local/cuda/bin/nvcc不一致

**Comment by campper** [comment]
> 你可以看看which cuda，看是不是cuda路径和上面编译调用的/usr/local/cuda/bin/nvcc不一致

好的，非常感谢，我再试试

**Comment by campper** [comment]
我重新安装了cuda10 和 对应的nvcc
重新进入到bottom_up_attention/caffe后 又将cuda10/include/cudnn.h 拷贝到 bottom-up-attention/caffe/include/caffe/util/ ，然后报 找不到nccl.h
我又按照网上教程安装了nccl
git clone https://github.com/NVIDIA/nccl.git
cd nccl
sudo make install -j4
sudo ldconfig
之后比较顺利的对caffe进行了编译，但又报
![image](https://user-images.githubusercontent.com/12744186/88210685-257fb880-cc87-11ea-9297-cb7b3feb0302.png)

make: Nothing to be done for 'all'.
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
python/caffe/_caffe.cpp:1:10: fatal error: Python.h: No such file or directory
 #include <Python.h>  // NOLINT(build/include_alpha)
          ^~~~~~~~~~
compilation terminated.
Makefile:507: recipe for target 'python/caffe/_caffe.so' failed
make: *** [python/caffe/_caffe.so] Error 1

**Comment by jackroos** [comment]
你可以试试
```bash
locate Python.h
```

**Comment by campper** [comment]
你好，我通过sudo apt install libboost-python-dev 解决了
![image](https://user-images.githubusercontent.com/12744186/90011398-1f07be00-dcd4-11ea-86ef-2e658e4b8a9a.png)
然后我在测试caffe是否安装成功时，报
![image](https://user-images.githubusercontent.com/12744186/90011490-42cb0400-dcd4-11ea-830c-985007bfd07b.png)
我在bottom_up_attention 看readme.md要求的python环境是2.7 整个系统环境是cuda9.0，不太明白caffe为什么要libcudart.so.10.0

**Comment by campper** [comment]
> caffe

终于搞定了。python2进入python后 pip install -r requirements 把该装的包装好就不错了。不容易。
谢谢，还想请教一下，我能不能直接通过model/pretrain_model 对自己的图片进行预测？

**Comment by jackroos** [comment]
你是指bottom_up_attention吗？

**Comment by campper** [comment]
> 你是指bottom_up_attention吗？
不是，是否能直接对我自己收集的图片通过您提供的模型进行image caption,还是必须要训练一遍。

**Comment by jackroos** [comment]
我们的预训练模型并没有image captioning的功能，你需要自己在你的数据训练。
