### ISSUE TITLE
some question about the codes in ./common/faster_rcnn.py

### ISSUE THREAD

**Issue by SnoopyMark** [jackroos/VL-BERT#44]
Hi, there. I read some of your codes and have some questions about class FastRCNN in file './common/faster_rcnn.py'. As we can see, it's forward method has args like `(self, images, boxes, box_mask, im_info, classes=None, segms=None, mvrc_ops=None, mask_visual_embed=None)`, but isn't it Faster-RCNN's work to get the RoIs, so why is there parameters like 'boxes' and so on?

**Comment by jackroos** [comment]
Actually, we drop the RPN branch of Faster RCNN in our VL-BERT since how to tune it is non-trivial in our case, we use Fast RCNN in our VL-BERT instead of Faster RCNN, the difference is that Fast RCNN doesn't have RPN so we need to input the boxes precomputed by pre-trained Faster RCNN.
