### ISSUE TITLE
Obtaining visual features for the ConceptualCaptions data set

### ISSUE THREAD

**Issue by jules-samaran** [jackroos/VL-BERT#50]
Hi,
I'd like to take a look at the pretraining but I was wondering if there was a way to have access to the train_frcnn.zip files without having to run the caffe model, are they available somewhere?
Best,

**Comment by jackroos** [comment]
Sorry about that. The files are too big to upload to online disks like Google Drive. You need to run the caffe code to extract the visual features.

**Comment by yonatanbitton** [comment]
+1 - I need this as well, and having problems with the caffe model. Opening an issue for it.
@jules-samaran were you manage to extract the features?
