### ISSUE TITLE
Is the roialign part forgotten compiled ?

### ISSUE THREAD

**Issue by Liu0329** [jackroos/VL-BERT#51]
It seems that the setup.py only compiles roipooling but not roialign.

**Comment by jackroos** [comment]
Both would be compiled since RoI align is also contained in [this folder](https://github.com/jackroos/VL-BERT/tree/master/common/lib/roi_pooling).

**Comment by Liu0329** [comment]
But there is only roipooling.so generated

**Comment by Liu0329** [comment]
I added the roi-align part in setup.py and it works
