### ISSUE TITLE
How is vgbua_res101_precomputed generated?

### ISSUE THREAD

**Issue by lmd1993** [jackroos/VL-BERT#57]
I have a question about how the vgbua_res101_precomputed is generated. Is it generated by ground truth regions and you run the Fast R-CNN to convert the regions to vectors (features)? Thanks.

**Comment by jackroos** [comment]
@lmd1993 No. It is generated by running inference of pre-trained Faster RCNN (provided on [this repo](https://github.com/peteanderson80/bottom-up-attention))  on COCO images. Both boxes and features are obtained by the Faster RCNN, while ground-truth regions are not utilized.
