### ISSUE TITLE
Why cannot import name 'C_ROIPooling' from 'common.lib.roi_pooling'

### ISSUE THREAD

**Issue by wenhao7841** [jackroos/VL-BERT#59]
I meet this problem:
ImportError: cannot import name 'C_ROIPooling' from 'common.lib.roi_pooling' (/home/wenhao/project/VL-BERT-master/pretrain/../common/lib/roi_pooling/__init__.py)
And I don't know how to solve.plz.

**Comment by haozidede** [comment]
compile with command: ./scripts/init.sh

**Comment by jackroos** [comment]
> compile with command: ./scripts/init.sh

@haozidede Thanks for your kind reply.
@WorthHouse You need to run the ./scripts/init.sh to compile the operators.

**Comment by betterze** [comment]
In code, common/lib/roi_pooling/roi_align.py, it does

```
from . import C_ROIPooling
```

it outputs error

```
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
```

I try to run the following code again, 

```
./scripts/init.sh
```

it outputs 

```
running build_ext
building 'C_ROIPooling' extension
Emitting ninja build file /cs/labs/danix/wuzongze/Gan_Manipulation/VL-BERT/common/lib/roi_pooling/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /cs/labs/danix/wuzongze/Gan_Manipulation/VL-BERT/common/lib/roi_pooling/build/temp.linux-x86_64-3.7/cs/labs/danix/wuzongze/Gan_Manipulation/VL-BERT/common/lib/roi_pooling/vision.o /cs/labs/danix/wuzongze/Gan_Manipulation/VL-BERT/common/lib/roi_pooling/build/temp.linux-x86_64-3.7/cs/labs/danix/wuzongze/Gan_Manipulation/VL-BERT/common/lib/roi_pooling/cpu/ROIAlign_cpu.o -L/cs/labs/danix/wuzongze/pythonV/venv3.7/lib/python3.7/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.7/C_ROIPooling.cpython-37m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.7/C_ROIPooling.cpython-37m-x86_64-linux-gnu.so -> 
```

It seems my installation is correct. Could you @huangyz0918 @jackroos  tell me why this error happen?

Thank you in advance.

**Comment by xinli2008** [comment]
have you soloved this problem? @betterze

**Comment by betterze** [comment]
@shaoniana1997 Unfortunately, I could not solve it.

**Comment by xarcsaber** [comment]
Found a solution for it.

Modify the following files:

- /RVL-BERT-master/common/lib/roi_pooling/roi_align.py
- /RVL-BERT-master/common/lib/roi_pooling/roi_pool.py

by commenting out the line "from . import C_ROIPooling" (should be line 8 for both)

At least the script works for me then...if it happens to lead to another error later on, I will edit my comment.
