### ISSUE TITLE
undefined symbol:  _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by search-opensource-space** [jackroos/VL-BERT#6]
when running the command "./scripts/dist_run_single.sh 4 vcr/train_end2end.py ./cfgs/vcr/base_q2a_4x16G_fp32.yaml ./"

I got this error 
--------------

ImportError: /data/workspace/VL-BERT/vcr/../common/lib/roi_pooling/C_ROIPooling.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
Traceback (most recent call last):
  File "./scripts/launch.py", line 200, in <module>
    main()
  File "./scripts/launch.py", line 196, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/vl-bert/bin/python', '-u', 'vcr/train_end2end.py', '--cfg', './cfgs/vcr/base_q2a_4x16G_fp32.yaml', '--model-dir', './', '--dist']' returned non-zero exit status 1.
(vl-bert) root@6cbe3808c2b8:/data/workspace/VL-BERT# Traceback (most recent call last):
  File "vcr/train_end2end.py", line 8, in <module>
    from vcr.function.train import train_net
  File "/data/workspace/VL-BERT/vcr/../vcr/function/train.py", line 26, in <module>
    from vcr.modules import *
  File "/data/workspace/VL-BERT/vcr/../vcr/modules/__init__.py", line 1, in <module>
    from .resnet_vlbert_for_vcr import ResNetVLBERT
  File "/data/workspace/VL-BERT/vcr/../vcr/modules/resnet_vlbert_for_vcr.py", line 7, in <module>
    from common.fast_rcnn import FastRCNN
  File "/data/workspace/VL-BERT/vcr/../common/fast_rcnn.py", line 10, in <module>
    from common.lib.roi_pooling.roi_pool import ROIPool
  File "/data/workspace/VL-BERT/vcr/../common/lib/roi_pooling/__init__.py", line 1, in <module>
    from .roi_align import ROIAlign
  File "/data/workspace/VL-BERT/vcr/../common/lib/roi_pooling/roi_align.py", line 8, in <module>
    from . import C_ROIPooling
ImportError: /data/workspace/VL-BERT/vcr/../common/lib/roi_pooling/C_ROIPooling.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
Traceback (most recent call last):
  File "vcr/train_end2end.py", line 8, in <module>
    from vcr.function.train import train_net
  File "/data/workspace/VL-BERT/vcr/../vcr/function/train.py", line 26, in <module>
    from vcr.modules import *
  File "/data/workspace/VL-BERT/vcr/../vcr/modules/__init__.py", line 1, in <module>
    from .resnet_vlbert_for_vcr import ResNetVLBERT
  File "/data/workspace/VL-BERT/vcr/../vcr/modules/resnet_vlbert_for_vcr.py", line 7, in <module>
    from common.fast_rcnn import FastRCNN
  File "/data/workspace/VL-BERT/vcr/../common/fast_rcnn.py", line 10, in <module>
    from common.lib.roi_pooling.roi_pool import ROIPool
  File "/data/workspace/VL-BERT/vcr/../common/lib/roi_pooling/__init__.py", line 1, in <module>
    from .roi_align import ROIAlign
  File "/data/workspace/VL-BERT/vcr/../common/lib/roi_pooling/roi_align.py", line 8, in <module>
    from . import C_ROIPooling

-----------------

I think it may be caused by ROI_pooling.xx.so

But I've compiled C_ROIPooling.cpython-36m-x86_64-linux-gnu.so  with "./scripts/init.sh"

**Comment by jackroos** [comment]
I also met this error in some environment, it seems that some python dependency makes the compiling failed, I solved it by creating a new conda environment and install dependencies as described in README. Could you try to create a new environment and try again? Thanks!

**Comment by jackroos** [comment]
Also, you can try the new requirements.txt that I just updated.

**Comment by search-opensource-space** [comment]
> Also, you can try the new requirements.txt that I just updated.

I have tried the new requirements.txt. But it doesnot work as well

**Comment by jackroos** [comment]
@search-opensource-space Could you please check the version of nvcc and gcc by:
```
nvcc -V
gcc --version
```
Thanks!

**Comment by search-opensource-space** [comment]
> @search-opensource-space Could you please check the version of nvcc and gcc by:
> 
> ```
> nvcc -V
> gcc --version
> ```
> 
> Thanks!

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.9.4/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-4.9.4/configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 4.9.4 (GCC)

**Comment by jackroos** [comment]
@search-opensource-space What's the version of your system, pytorch and torchvision?

**Comment by wangshuwch** [comment]
i have the same error, the version of gcc and nvcc  as same as @search-opensource-space ,my system is centos7.5, python 3.6.10, pytorch 1.10, torchvision 0.2.1

**Comment by jackroos** [comment]
@wangshuwch I only test the code under Ubuntu 16.04.

**Comment by becxer** [comment]
I have the same issue with this. Does anyone figure out what is the problem?

**Comment by becxer** [comment]
In my case, I resolved this by upgrading gcc 4.9.3 to 5.4.0 :) 

And, I don't know why successfully building roi_pooling using "./scripts/init.sh"  instead of building in the exact directory.

**Comment by jackroos** [comment]
@becxer Actually in the './scripts/init.sh', it would enter the directory firstly and then compile the operators.

**Comment by becxer** [comment]
@jackroos Yes I know, It sounds weird but doing it manually gives the same error :(
