### ISSUE TITLE
fatal error: torch/extension.h: No such file or directory

### ISSUE THREAD

**Issue by whqwill** [jackroos/VL-BERT#64]
When I run ./scripts/init.sh, it shows:
    /opt/mnt/haiqing/Project/VL-BERT-HAKE/common/lib/roi_pooling/cpu/vision.h:3:29: fatal error: torch/extension.h: No such file or directory
How to solve it?

**Comment by alice-cool** [comment]
Good luck to you
https://blog.csdn.net/abcd740181246/article/details/83058511

**Comment by alice-cool** [comment]
Could you solve it , I find the same error?

**Comment by Jiejiegary** [comment]
@whqwill Hi, May I know how did you fix the issue? My Pytorch version is 1.4 but I still have this bug.
