### ISSUE TITLE
attention_viz 

### ISSUE THREAD

**Issue by detectiveli** [jackroos/VL-BERT#7]
Dear contributor,

Fantastic work on VL task!

Now I have some trouble showing the visualization results between language and ROIs. Could you please hit me your code to generate the result as attention_viz.png showed if possible?

Many thanks.

**Comment by jackroos** [comment]
Thanks for your interest! The visualization is based on [bertviz](https://github.com/jessevig/bertviz), I would like to share my code but it may be several days after, you can try to modify the code of bertviz first. Thanks!

**Comment by detectiveli** [comment]
Good point and looking forward to your code : )

**Comment by jackroos** [comment]
@detectiveli The code of visualization has been added. And currently I provide 100 pre-computed examples. The code for pre-computing attention maps would be added soon.

**Comment by detectiveli** [comment]
Fantastic work and your code really help a lot! Thanks!

**Comment by tomeramit** [comment]
Can you upload the code that creates the visualization? I'm trying to create this code and it will be very helpful to get it

**Comment by jackroos** [comment]
@tomeramit Do you mean the code for computing attention maps?

**Comment by tomeramit** [comment]
yes, just reminding that it can help :) 
(when you wrote: The code for pre-computing attention maps would be added soon.)

**Comment by jackroos** [comment]
Sorry for that, I would add the code ASAP. Thanks for reminding me!

**Comment by jackroos** [comment]
@tomeramit Now you can switch to [attention_viz branch](https://github.com/jackroos/VL-BERT/tree/attention_viz) for computing attention maps, I would merge it into master branch after I test the code to make sure everything works ok. If you find any problems in using the code, plz let me know! Thanks!

**Comment by jackroos** [comment]
Just merged attention computing code! If you don't have any other questions, I would close this issue. Thanks!

**Comment by tomeramit** [comment]
thanks!
