### ISSUE TITLE
About adding whole image as a bounding box & the embedding for [END] token

### ISSUE THREAD

**Issue by coldmanck** [jackroos/VL-BERT#8]
Thank you for your brilliant work. 
1. According to Figure 1 in the paper, for Visual Feature Embedding of image regions, VL-BERT is using features of bounding box proposals. It seems you are concatenating the whole image with other bounding boxes in every `dataset.py` by assigning `add_image_as_a_box=True` (e.g. [VQA](https://github.com/jackroos/VL-BERT/blob/33f9bc6d8197d09cd84c03fe125a9e8c27fd132b/vqa/data/datasets/vqa.py#L213)). In my understanding, your code utilizes this first box (whole image) for Visual Feature Embedding of words other than image regions (with `[IMG]` token). However, it seems your code didn't remove this full image box after that so there's one additional (full image) box at the front of `boxes`? 
2. I can't see why it make sense to just train a joint new (Token + Visual Feature) Embedding for the final word `[END]` (e.g. in [class VisualLinguisticBert](https://github.com/jackroos/VL-BERT/blob/33f9bc6d8197d09cd84c03fe125a9e8c27fd132b/common/visual_linguistic_bert.py#L213))? It neither used predefined `[END]` token like `[SEP]` and `[CLS]` nor used the full image box as Visual Feature embedding. Did I miss anything here?

**Comment by jackroos** [comment]
1. We do use the whole image as the first box in implementation, and it is just a design choice.
2. The [END] token is just a special token, it means the end of the sequence, like [SEP] in BERT. You can refer to [this paper](https://arxiv.org/pdf/1906.04341.pdf) for the effect of such kind of special tokens. And whether to add visual embedding in it, I think, would not influence too much.
Thanks!

**Comment by coldmanck** [comment]
@jackroos Thanks for your prompt reply! I see. I am convinced of the first point but I think for the second point it's a bit misleading for your figure :-) Maybe you would like to clarify it in your paper.
